version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:

  hydra-migrate:
    image: oryd/hydra:v1.0.8
    command: migrate sql -e -y
    depends_on:
      - postgres
    networks:
      default:
      reaction:
    env_file: ".env"
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.0.8
    command: serve all --dangerous-force-http
    depends_on:
      - hydra-migrate
      - postgres
    networks:
      default:
      reaction:
    ports:
      # Public port
      - "4444:4444"
      # Admin port
      - "4445:4445"
      # Port for hydra token user
      - "5555:5555"
    env_file: ".env"
    restart: unless-stopped

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=hydra
    networks:
      default:
      reaction:
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
